# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Andrew Richardson
tagline:          
description:      'iOS Developer & Student'
url:              http://hyde.getpoole.com

author:
  name:           'Andrew Richardson'
  url:            https://twitter.com/nosdrew

paginate:         5

# Custom vars
github:
  repo:           https://github.com/poole/hyde